In [ ]:
# any , all

In [2]:
a = [1, 0, 0, 2, 3]
print(any(a))
print(all(a))

True
False


In [8]:
print(any([x == 3 for x in a]))
print(all([x == 3 for x in a]))
print(any(x > 3 for x in a))
print(all(x > 3 for x in a))

True
False
False
False


In [9]:
# max , min

In [17]:
a = [1, -2, 3, 4, -5, 7, 8, 9, -10]
print(min(a))

# if we have a bool list: max = any and min = all
b = [1, 1, 1, 0, 0, 0, 1, 1, 0, 1]
print(min(b), all(b))

# want to get min in power 2 of these.
print(min(a, key=lambda x: x ** 2))
print(max(a, key=lambda x: x % 7))
print(min(a, key=lambda x: x % 7))

-10
0 False
1
-2
7


In [24]:
data = [
    {"name": "a", "age": 10, "revenue": 100},
    {"name": "b", "age": 20, "revenue": 90},
    {"name": "c", "age": 30, "revenue": 80},
    {"name": "d", "age": 40, "revenue": 70}
]

# oldest
print("oldest", max(data, key=lambda item: item["age"]))
print("richest", max(data, key=lambda item: item["revenue"]))
print("efficient", max(data, key=lambda x: x["revenue"] / x["age"]))

oldest {'name': 'd', 'age': 40, 'revenue': 70}
richest {'name': 'a', 'age': 10, 'revenue': 100}
efficient {'name': 'a', 'age': 10, 'revenue': 100}


In [25]:
def get_something(x):
    return x["age"]


print(max(data, key=get_something))

{'name': 'd', 'age': 40, 'revenue': 70}


In [26]:
# sum , len

In [27]:
print(a)
print(sum(a))
print(sum(a, start=10))

[1, -2, 3, 4, -5, 7, 8, 9, -10]
15
25


In [30]:
print(sum(range(1, 101)) / len(range(1, 101)))
print(sum(range(1, 101)))

50.5
5050


In [31]:
import math

math.fsum([1, 2, 3, 4])

10.0

In [1]:
# hash
# print(hex(hash("FaraDars")))
# print(hex(hash("FaraDars2")))
# print(hex(hash("Faraars")))
# print(hex(hash("araDars")))
print(hash("FaraDars"))
print(hash("FaraDars2"))
print(hash("Faraars"))
print(hash("araDars"))

-3101165086233532212
7088914162221605601
924841026244318769
-5715804182075701554


In [44]:
a = [1, 2, 3]
b = a
c = a.copy()
print(hash(tuple(a)))
print(hash(tuple(b)))
print(hash(tuple(c)))

529344067295497451
529344067295497451
529344067295497451


In [45]:
# copy 

In [46]:
import copy

a = [[1, 2], [3, 4], [5, 6]]
b = copy.copy(a)
a[1][0] = 100
b

[[1, 2], [100, 4], [5, 6]]

In [47]:
a = [[1, 2], [3, 4], [5, 6]]
b = a.copy()
a[1][0] = 100
b = 

[[1, 2], [100, 4], [5, 6]]

In [48]:
# deep copy
import copy

a = [[1, 2], [3, 4], [5, 6]]
b = copy.deepcopy(a)
a[1][0] = 100
b

[[1, 2], [3, 4], [5, 6]]

In [49]:
import numpy as np
a = np.array(a)
print(a)

[[  1   2]
 [100   4]
 [  5   6]]


In [50]:
b = a.copy()
a[1][0] = 200
a

array([[  1,   2],
       [200,   4],
       [  5,   6]])

In [51]:
b

array([[  1,   2],
       [100,   4],
       [  5,   6]])

In [52]:
# decimal

In [56]:
from decimal import Decimal
print(1/7)
print(Decimal("1")/ Decimal("7"))

print(0.1+0.2)
print(Decimal(0.1) + Decimal(0.2))
print(Decimal("0.1") + Decimal("0.2"))


0.14285714285714285
0.1428571428571428571428571429
0.30000000000000004
0.3000000000000000166533453694
0.3


In [14]:
from decimal import getcontext, Decimal
getcontext().prec = 100

In [15]:
print(1/7)
print(Decimal("1")/ Decimal("7"))

print(0.1+0.2)
print(Decimal(0.1) + Decimal(0.2))
print(Decimal("0.1") + Decimal("0.2"))


0.14285714285714285
0.1428571428571428571428571428571428571428571428571428571428571428571428571428571428571428571428571429
0.30000000000000004
0.3000000000000000166533453693773481063544750213623046875
0.3


In [11]:
print(len("0.1428571428571428571428571428571428571428571428571428571428571428571428571428571428571428571428571429"))
print(len("0.3000000000000000166533453693773481063544750213623046875"))

102
57


In [61]:
from decimal import localcontext


In [63]:
with localcontext() as c:
    c.prec = 100
    print(Decimal("0.1") / Decimal("0.7"))

0.1428571428571428571428571428571428571428571428571428571428571428571428571428571428571428571428571429


In [64]:
print("a")

a


In [65]:
print(print(print("a")))

a
None
None
