In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from modular import dataloader, models, gravity
import numpy as np
import pandas as pd

In [4]:
city_path = r"/mnt/Data1/Python_Projects/Pure-Python/P5/01-Thesis/data/Anaheim"
data = dataloader.Custom_DataLoader(city_name="Anaheim", city_path=city_path)
data.fit()

In [5]:
data.data

origin  dest  demand  production  attraction      cost
0          1     2  1365.9      7074.9     13602.2  0.068284
1          1     3   407.4      7074.9      5676.6  0.121725
2          1     4   861.4      7074.9     10223.9  0.103969
3          1     5   354.4      7074.9      4644.2  0.162597
4          1     6   545.1      7074.9      6522.2  0.128555
...      ...   ...     ...         ...         ...       ...
1401      38    33    24.6      1511.8      1036.2  0.057720
1402      38    34    31.1      1511.8      1669.9  0.060831
1403      38    35    21.4      1511.8      1125.8  0.022637
1404      38    36    19.1      1511.8       964.7  0.030434
1405      38    37     2.3      1511.8       228.8  0.058275

[1406 rows x 6 columns]

In [200]:
import numpy as np

def exponential_decay(d, beta):
    return np.where(d > 0, np.exp(-beta * d), 0)

model = gravity.GravityModel(decay_function=exponential_decay, param_names=["beta"])

model.fit(data.data, decay_params={"beta": 0.1})

# Or calibrate the parameter
params = model.calibrate(data.data, initial_params={"beta": 0.1}, bounds=[(0.01, 200)])
print("Best beta:", params["beta"])


Best beta: 1.4766855393390064


In [197]:
pd.DataFrame(model.OD_matrix)

0            1           2            3           4           5   \
0      0.000000  1040.741911  401.899493   739.683783  315.601856  458.272431   
1    939.849393     0.000000  616.043819  1100.568864  448.223103  637.606509   
2    629.606793  1068.681595    0.000000   902.251569  331.894269  458.612569   
3   1056.099810  1740.046559  822.308098     0.000000  563.142617  774.813470   
4    204.959771   322.335467  137.586836   256.146605    0.000000  176.573289   
5    545.868305   841.010985  348.704984   646.401628  323.862062    0.000000   
6    586.637914   901.780104  372.036465   688.582861  339.397447  603.686220   
7     55.746852    85.458876   35.223192    65.235811   31.975149   56.058208   
8    181.264460   274.000239  112.190700   208.126661   98.780887  156.307948   
9     12.862715    18.851318    7.617220    14.137001    6.406675    9.602919   
10    49.514846    63.030431   24.688781    45.617880   19.568203   28.458549   
11    47.284581    67.693058   25.373066    46.369258   19.599066   28.346150   
12     3.246998     5.410279    1.960835     3.568279    1.464758    2.094713   
13     9.910757    18.020551    7.227650    12.601318    4.936848    6.939465   
14    33.148829    57.913135   26.446596    44.454421   16.926629   23.621629   
15    18.967069    31.679373   16.102893    29.608979   10.094521   13.896828   
16    50.241608    81.618628   37.332907    77.559459   27.292688   37.345355   
17   223.797217   357.588070  158.283026   302.128534  131.977826  174.896404   
18    79.274969   125.758526   54.734625   102.877030   50.685142   64.314566   
19    40.579681    64.230754   27.735909    51.784842   28.142743   33.738089   
20   203.812305   318.715934  135.070247   251.442749  147.131478  180.602365   
21   117.925232   182.988426   76.732295   142.622801   75.344565  112.157566   
22   116.107405   179.306698   74.606245   138.403563   70.339367  126.570691   
23    29.796849    50.885299   22.275673    40.187358   15.016858   21.001724   
24   771.405288  1348.012421  519.060414   940.394238  371.050836  524.573323   
25   267.453044   431.422532  157.041138   285.991251  118.395558  169.816158   
26    44.857974    70.782388   29.792396    56.959297   22.464948   31.569115   
27   180.381049   276.202577  112.192971   210.589675   85.798662  121.914923   
28   107.098610   149.371905   59.510458   110.350761   48.285605   70.805679   
29   233.080175   366.818720  158.951241   303.885179  134.784408  181.937243   
30   305.936376   471.665525  199.382241   379.668579  163.994127  229.846800   
31   172.953847   258.390680  106.400776   199.486944   89.333020  129.845672   
32   152.602120   224.106262   90.829266   168.829951   76.482598  114.259202   
33   411.393689   644.994799  276.667515   520.485668  263.228262  339.544272   
34   155.089359   238.079671   99.661350   186.510293   91.178636  132.515381   
35    75.428218   114.106484   46.821965    86.946167   41.365991   65.298931   
36    25.449933    39.905335   17.061988    31.944484   17.505719   21.511415   
37   120.143757   184.408919   76.753101   142.916506   71.146946  112.079549   

            6         7           8           9   ...          28          29  \
0   351.086823  2.630808   61.608882   91.719145  ...  160.113936  193.734839   
1   487.371661  3.642010   84.100162  121.390381  ...  201.664494  275.339870   
2   348.804323  2.604051   59.736458   85.089459  ...  139.376817  206.975176   
3   588.382137  4.395555  100.999041  143.927403  ...  235.548044  360.637413   
4   131.911316  0.979965   21.803824   29.668059  ...   46.880481   72.756387   
5   430.348023  3.151172   63.281370   81.563296  ...  126.089099  180.130870   
6     0.000000  3.684729   68.672606   87.864418  ...  135.497597  190.713256   
7    46.728428  0.000000    6.664374    8.400927  ...   12.905938   18.086776   
8   120.919757  0.925332    0.000000   28.390414  ...   42.490667   57.622383   
9     7.374458  0.055599    1.353241    0.0

In [198]:
pd.DataFrame(model.observed_OD)


0       1      2       3      4      5      6    7     8      9   ...  \
0      0.0  1365.9  407.4   861.4  354.4  545.1  431.5  1.0  56.8   75.3  ...   
1   1171.2     0.0  608.1  1271.4  542.3  808.4  629.1  1.0  74.9   87.3  ...   
2    721.1  1237.9    0.0  1107.9  386.6  582.8  457.9  1.0  57.1   62.4  ...   
3   1222.5  2106.7  938.6     0.0  665.9  988.8  769.8  1.0  91.6  108.6  ...   
4    243.4   419.2  145.3   311.6    0.0  195.6  158.7  1.0  19.8   21.3  ...   
5    637.4  1089.9  381.8   812.1  338.2    0.0  477.9  1.0  73.6   54.3  ...   
6    682.3  1191.8  431.1   883.4  379.6  646.4    0.0  1.0  63.3   74.6  ...   
7     44.3    95.3    1.3    28.1   26.6   33.8   35.8  0.0  13.8    1.5  ...   
8    198.6   293.5  132.6   201.4   75.9  157.6   99.3  1.0   0.0   49.8  ...   
9     12.3    21.1    9.5    13.1    5.8   11.1    5.8  1.0   1.0    0.0  ...   
10    35.8    58.8   22.8    45.8   12.0   14.8   21.1  1.0   1.0   17.8  ...   
11    35.2    61.4   19.8    44.7   15.9   23.2   17.3  1.0   2.6    7.1  ...   
12     1.0     1.0    1.0     1.0    1.0    1.0    1.0  1.0   1.0    1.0  ...   
13     9.8    16.8    9.0    14.3    4.5    5.8    4.3  1.0   1.0    1.5  ...   
14    33.8    61.8   33.3    51.5   16.8   21.8   14.3  1.0   1.0    7.3  ...   
15    17.4    29.2   11.6    22.6   11.3   11.1    8.0  1.0   1.3    1.0  ...   
16    55.3    88.3   58.0    86.0   31.1   33.8   21.5  1.0   1.0    7.3  ...   
17   181.1   311.6  201.8   334.7  136.8  135.4  109.2  1.0  11.8   39.6  ...   
18    58.1    96.8   44.8    97.2   39.7   47.3   36.9  1.0  16.1   11.1  ...   
19    25.5    57.8    1.0    31.1   25.3   18.1   25.3  1.0   7.1    2.5  ...   
20   141.9   261.1   71.5   173.8  103.4  136.0  137.5  1.0  42.3   32.3  ...   
21    86.0   151.8   53.6   112.8   64.1   89.4   74.9  1.0  21.5   18.6  ...   
22   119.2   197.1   56.9   116.0   53.2  109.6   66.7  1.0  11.8   11.6  ...   
23    29.8    51.3   29.8    44.3   13.6   18.5   12.3  1.0   1.0    9.8  ...   
24   796.8  1232.3  819.0  1232.4  333.6  517.8  283.8  1.0   1.0   91.8  ...   
25   244.6   383.6  241.8   372.0  101.9  155.7   92.4  1.0   2.1   38.4  ...   
26    39.3    64.1   33.8    54.9   22.8   33.4   22.2  1.0   1.0    7.0  ...   
27   135.4   238.8   89.3   179.4   78.1  116.3   86.7  1.0  24.1   26.6  ...   
28    91.6   132.6   55.0    95.1   36.3   88.3   41.6  1.0   6.1    2.0  ...   
29   143.3   314.5   89.1   219.3  131.1  105.9  106.3  1.0  21.6   59.3  ...   
30   248.7   416.3  178.1   332.5  135.6  203.3  148.4  1.0  35.4   51.1  ...   
31   141.2   241.5  102.1   191.7   79.7  114.7   85.5  1.0  21.3   31.8  ...   
32   131.2   221.4   71.6   134.9   53.7  101.9   82.0  1.0  23.9   32.6  ...   
33   256.3   507.2  136.8   388.4  206.3  181.2  208.4  1.0  77.8   57.1  ...   
34   146.2   247.5   93.5   156.8   68.1  121.7   82.4  1.0   6.8   32.5  ...   
35    59.4   111.9   19.3    53.5   29.0   42.8   44.6  1.0  12.9    5.0  ...   
36    19.8    31.8   21.3    34.1   12.6   14.6   12.1  1.0   6.8    3.0  ...   
37   111.2   192.6   55.3   112.7   51.4   89.2   71.1  1.0  19.6   17.6  ...   

       28     29     30     31    32     33     34     35    36     37  
0   139.1  119.1  295.6   85.9  74.3   96.4   53.6   37.9  13.7  107.7  
1   194.1  194.8  329.9   95.1  79.1  134.9   81.3   55.1  19.6  166.9  
2   109.6  132.1  234.5   69.9  61.1  101.6   58.7   43.4  13.6  116.9  
3   179.9  301.6  508.9  119.4  94.3  167.5   98.7   74.6  21.7  199.9  
4    41.6   57.1  109.7   24.6  22.6   45.7   21.6   11.4   7.0   38.5  
5   101.6  108.6  281.4   82.6  72.6   88.6   67.7   47.3  13.9  132.7  
6   101.9  139.8  295.2   86.4  73.4   92.4   72.4   55.6   9.7  156.9  
7    17.4   17.1   51.6    7.4  19.3    5.1    6.3    1.3   1.0   41.8  
8    42.6   63.0   59.1   43.8   8.5   41.4   31.3   43.1   7.1   44.1  
9     2.0    4.0    3.3    3.3   1.0    2.0    2.5    2.3   1.3    3.8  
10   18.0   11.8   25.1    5.5   1.0   16.3  

In [199]:
np.sqrt(np.mean((model.observed_OD - model.OD_matrix) ** 2))

38.622320870734214

In [193]:
data.data

origin  dest  demand  production  attraction      cost
0          1     2  1365.9      7074.9     13602.2  0.068284
1          1     3   407.4      7074.9      5676.6  0.121725
2          1     4   861.4      7074.9     10223.9  0.103969
3          1     5   354.4      7074.9      4644.2  0.162597
4          1     6   545.1      7074.9      6522.2  0.128555
...      ...   ...     ...         ...         ...       ...
1401      38    33    24.6      1511.8      1036.2  0.057720
1402      38    34    31.1      1511.8      1669.9  0.060831
1403      38    35    21.4      1511.8      1125.8  0.022637
1404      38    36    19.1      1511.8       964.7  0.030434
1405      38    37     2.3      1511.8       228.8  0.058275

[1406 rows x 6 columns]

In [205]:
import torch.nn as nn
from torch import optim
from tqdm.auto import tqdm

model_gravity = models.GravityNet()
optimizer = optim.Adam(model_gravity.parameters(), lr=0.001)
loss_fn = nn.MSELoss()

# Training
for epoch in tqdm(range(100)):
    for x, y in data.dataloader:
        optimizer.zero_grad()
        y_hat = model_gravity(x[:, 0], x[:, 1], x[:, 2])
        loss = loss_fn(y_hat, y)
        loss.backward()
        optimizer.step()
    
    if epoch % 1 == 0:
        print(f"Epoch {epoch}: Loss = {loss.item():.4f}, Beta = {model_gravity.beta.item():.4f}, k = {model_gravity.k.item():.4f}")

  0%|          | 0/100 [00:00<?, ?it/s]

tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([7074.8999])
tensor([9662.5000])
tensor([9662.5000])
tensor([9662.5000])
tensor([9662.5000])
tensor([9662.5000])
tensor([9662.5000])
tensor([9662.5000])
tensor([9662.5000])
tensor([9662.5000])
tensor([9662.5000])
tensor([9662.5000])
tensor([9662.5000])
tensor([9662.5000])


KeyboardInterrupt: 

In [1]:
0.6459*2

1.2918